name: flutter_water
description: Flutter water.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1
author: Caden <17719916361@163.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Toastプラグイン https://github.com/OpenFlutter/flutter_oktoast
  oktoast: ^3.0.0
  # ネットプラグイン https://github.com/flutterchina/dio
  dio: ^4.0.0
  # ルーティングフレームワーク https://github.com/theyakka/fluro
  fluro: ^2.0.3
  # Dart 共通ツールライブラリ https://github.com/Sky24n/common_utils
  common_utils: 2.0.2
  url_launcher: 6.0.9
  # 图片选择插件（支持Web） https://github.com/flutter/plugins/tree/master/packages/image_picker
  image_picker: 0.8.2
  # 侧滑删除 https://github.com/letsar/flutter_slidable
  flutter_slidable: ^0.6.0
  # WebView插件 https://github.com/flutter/plugins/tree/master/packages/webview_flutter
  webview_flutter: 2.0.9
  # 处理键盘事件 https://github.com/diegoveloper/flutter_keyboard_actions
  keyboard_actions: ^3.4.0
  # 图片缓存 https://github.com/renefloor/flutter_cached_network_image
  cached_network_image: ^3.1.0
  # 格式化String https://github.com/Naddiseo/dart-sprintf
  sprintf: ^6.0.0
  # 状态管理 https://github.com/rrousselGit/provider
  provider: ^5.0.0
  # Flutter 常用工具类库 https://github.com/Sky24n/flustars
  flustars: ^2.0.1
  # 获取当前设备信息 https://github.com/fluttercommunity/plus_plugins/tree/main/packages/device_info_plus
  device_info_plus: 2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/data/
    - assets/images/
    - assets/images/home/
    - assets/images/login/

